version: '2'

services:
  test-db1:
    image: akomic/zbx-pgsql-agent:v1
    container_name: test-db1
    environment:
      - PG_LINE=hostname:5432:*:user:password
      - SERVER_IP=127.0.0.1
      - HOST_NAME=test-db1
      - LISTEN_PORT=20050
    network_mode: host
  test-db2:
    image: akomic/zbx-pgsql-agent:v1
    container_name: test-db2
    environment:
      - PG_LINE=hostname:5432:*:user:password
      - SERVER_IP=127.0.0.1
      - HOST_NAME=test-db2
      - LISTEN_PORT=20051
    network_mode: host
